Repository qicqock/db_webserver, pull requests merged in 2020-11, with the labels that each got.

#29 room 테이블 더미값 추가 + sql문
  sql/DATA.sql
Labels: back-end

#33 drop table 순서 변경, room instance 넣기 쿼리문
  sql/DATA.sql
  sql/init.sql
Labels: database

#58 Modify feature/register
  routes/index.js
  views/chanwoong/login.ejs
  views/chanwoong/register.ejs
Labels: front-end

#56 Feature/sql fk
  sql/DATA.sql
  sql/DATA2.sql
  sql/DATA3.sql
  sql/dummy.sql
  sql/init.sql
Labels: back-end

#83 generate Help
  public/stylesheets/css/help-table.css
  views/chanwoong/faq.ejs
  views/chanwoong/help.ejs
  views/chanwoong/uppermenu_header.ejs
Labels: front-end

#89 Modify feature/help
  views/chanwoong/faq.ejs
  views/chanwoong/help.ejs
Labels: front-end

#99 Generate Booking form & modify help
  app.js
  public/stylesheets/css/help-table.css
  routes/index.js
  views/.DS_Store
  views/chanwoong/booking.ejs
  views/chanwoong/help.ejs
  views/chanwoong/reservation.ejs
Labels: front-end

#113 modify mypage
  routes/myinfo.js
  views/chanwoong/myinfo.ejs
Labels: front-end
